/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cmzw (https://sketchfab.com/cmzw)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
title: Stylized planet
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/earth.gltf")
  const { actions } = useAnimations(animations, group)

  useFrame(() => {
    if (props.showMore && group.current.position.x < 4.75) {
      group.current.position.x += 0.25
    } else if (!props.showMore && group.current.position.x > 0) {
      group.current.position.x -= 0.25
    }
    group.current.rotation.y += 0.0025
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.54, -0.06, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Clouds_1">
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.Clouds}
                />
              </group>
              <group name="Planet_2">
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.Planet}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/earth.gltf")
